absolute_frame_count: 100
approx_secs: 30
categories:
- car
- person
- dog
directory: /home/pi/
frame_count_secs: absolute
max_imstorage: 10000
max_vidstorage: 10000
min_score: 0.6
model_preference: ssd_mobilenet_v3_small
notify_period: 5
variations_seed_native_stored: true
